# IBM Guestbook image version ibmcom/guestbook:v1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
name: teste

image:
  repository: ibmcom/guestbook
  tag: v1
  pullPolicy: Always

# For some dev env (like minikube), you may need to set the type to NodePort
service:
  name: srv-lr
  type: LoadBalancer
  port: 3000
  targetPort: 3000

#ingress:
#  name: igr-lr
#  enabled: true
#  className: ""
#  annotations: {nginx.ingress.kubernetes.io/rewrite-target: /}
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host:
#      paths:
#        - path: /
#          pathType: Prefix
  #tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local